openapi: "3.0.0"
info:
  title: "Karten_APP Routen-API"
  version: "1.0.0"
paths:
  /api/routes:
    get:
      summary: "Alle gespeicherten Routen abrufen"
      responses:
        '200':
          description: "Liste der Routen"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RouteWithID'
    post:
      summary: "Neue Route speichern"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Route'
      responses:
        '201':
          description: "Route erfolgreich erstellt"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
components:
  schemas:
    Route:
      type: object
      required: [name, start, end, path]
      properties:
        name:   { type: string }
        start:  { type: string }
        end:    { type: string }
        path:   { type: object }
    RouteWithID:
      allOf:
        - $ref: '#/components/schemas/Route'
        - type: object
          properties:
            id: { type: string }
